{
 "title": "Cloud Functions Monitoring",
 "tags": [
  "Compute",
  "Cloud Monitoring",
  "GCP"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "project",
    "label": "Project",
    "query": {}
   },
   {
    "name": "alignmentPeriod",
    "label": "Alignment Period",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Cloud Functions Monitoring",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard has 5 charts for the related [Cloud Functions metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-cloudfunctions), including `Active instances`, `Execution count`, `Execution times`, `Network egress`, and `Memory usage`."
   }
  },
  {
   "title": "Active instances",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_MEAN",
      "filters": [
       "resource.type",
       "=",
       "cloud_function"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudfunctions.googleapis.com/function/active_instances",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Execution count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "cloud_function"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudfunctions.googleapis.com/function/execution_count",
      "projectName": "$project",
      "unit": "1",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Execution times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "cloud_function"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudfunctions.googleapis.com/function/execution_times",
      "projectName": "$project",
      "unit": "ns",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "cloud_function"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudfunctions.googleapis.com/function/execution_times",
      "projectName": "$project",
      "unit": "ns",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_PERCENTILE_05",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "cloud_function"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudfunctions.googleapis.com/function/execution_times",
      "projectName": "$project",
      "unit": "ns",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  },
  {
   "title": "Network egress",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MAX",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "cloud_function"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudfunctions.googleapis.com/function/network_egress",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MIN",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "cloud_function"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudfunctions.googleapis.com/function/network_egress",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MEAN",
      "perSeriesAligner": "ALIGN_RATE",
      "filters": [
       "resource.type",
       "=",
       "cloud_function"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudfunctions.googleapis.com/function/network_egress",
      "projectName": "$project",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MAX",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "cloud_function"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudfunctions.googleapis.com/function/user_memory_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MIN",
      "perSeriesAligner": "ALIGN_PERCENTILE_99",
      "filters": [
       "resource.type",
       "=",
       "cloud_function"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudfunctions.googleapis.com/function/user_memory_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DISTRIBUTION"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "$alignmentPeriod",
      "crossSeriesReducer": "REDUCE_MEAN",
      "perSeriesAligner": "ALIGN_DELTA",
      "filters": [
       "resource.type",
       "=",
       "cloud_function"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudfunctions.googleapis.com/function/user_memory_bytes",
      "projectName": "$project",
      "unit": "By",
      "valueType": "DISTRIBUTION"
     }
    }
   ]
  }
 ]
}